#!/usr/bin/env python3
import os
import shutil
import io
import re

from tools.low.glob import *

from tools.low.readSymMap import *
from tools.pypstem._utils import *
from tools.pypstem.callProcess import *
from tools.pypstem.manSetup import setup_compiler

flags_asm = default_flags_comp
flags_asm.extend(default_flags_comp_asm)
if cfg.flags_compile:
    flags_asm.extend(cfg.flags_compile)
if cfg.flags_compile_asm:
    flags_asm.extend(cfg.flags_compile_asm)

def write_depend():
    # get all functions
    func_list = [sym[MapFmt.Symbol] or f"fn_{sym[MapFmt.Start]:08X}" for sym in read_sym_file() if "f" in sym[MapFmt.Type] and not sym[MapFmt.Rank] == "U"]

    # write depends.s
    in_depend = getBuildDependFile().with_suffix(".s")
    with open(in_depend, "w") as f:
        for func in func_list:
            f.write(f"    IMPORT {func}\n")
        if "__ctr_start" not in func_list: # pull the entry point in even before crt0 is decompiled
            f.write("    IMPORT __ctr_start\n")
        f.write("\n    PRESERVE8\n    END\n")

    # compile depends.o
    asm_flags = flags_asm + ["-o", str(getBuildDependFile()), str(in_depend)]
    do_assemble(asm_flags)

def find_scaffold_function_aliases():
    aliases = {}
    for module_path, module in cfg.modules.items():
        root = getProjDir() / module_path
        if not root.is_relative_to(getProjDir() / "Game") and not root.is_relative_to(getProjDir() / "lib"):
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix in (".c", ".cpp", ".h", ".hpp"):
                for name, address in re.findall(r"\b(fn_([0-9A-Fa-f]{8}))\b", path.read_bytes().decode("latin1")):
                    aliases.setdefault(int(address, 16), set()).add(name)
    return aliases

def write_stubs():
    # add stubs module
    cfg.modules[str(getSplitPath().relative_to(getProjDir()))] = {"name": getStubsLibName(), "extensions": set(["c"]), "source_dir": "."}

    getSplitPath().mkdir(parents=True, exist_ok=True)
    aliases = find_scaffold_function_aliases()

    # write stubs.c
    with io.StringIO() as f:
        f.write(f"/*\n\tStub file for {cfg.project_name}\n")
        f.write( "\tAutogenerated, please dont modify!\n*/\n\n")
        f.write("#define STUB(S) __weak __attribute__((section(\"i.\" #S))) void S() { return; }\n")
        f.write("#define STUB_G(S) __weak __attribute__((section(\"i.\" #S))) void S() { __nop(); __nop(); __nop(); }\n")
        f.write("#define STUB_ENTRY(S) __attribute__((section(\"i.\" #S))) void S() { __nop(); __nop(); __nop(); }\n")
        f.write( "\n")

        for sym in read_sym_file():
            if not "f" in sym[MapFmt.Type]:
                continue
            if "s" in sym[MapFmt.Type]:
                continue
            if "g" in sym[MapFmt.Type] and sym[MapFmt.Symbol] != "__ctr_start": # the entry point must exist for the link to succeed
                continue
            #if  "U" in sym[MapFmt.Rank]:
            #    continue

            func = sym[MapFmt.Symbol]
            size = sym[MapFmt.End] - sym[MapFmt.Start]
            if not func:
                # These are compact-image placeholders, not reconstructed code.
                # The identifier must encode an existing unnamed function row.
                names = aliases.get(sym[MapFmt.Start], set()).copy()
                if sym[MapFmt.Rank] != "U":
                    names.add(f"fn_{sym[MapFmt.Start]:08X}")
                for name in sorted(names):
                    f.write(f"/* Scaffold alias for unnamed function at 0x{sym[MapFmt.Start]:08X}. */\n")
                    f.write(f"{'STUB_G' if size > 4 else 'STUB'}({name});\n")
                continue

            if "g" in sym[MapFmt.Type]:
                f.write(f"STUB_ENTRY({func});\n")
            elif size > 4:
                f.write(f"STUB_G({func});\n")
            else:
                f.write(f"STUB({func});\n")
        content = f.getvalue()
    if not getStubsFile().exists() or getStubsFile().read_text() != content:
        getStubsFile().write_text(content)

def exec_split(clear=False):
    if not cfg.split:
        write_stubs()
        write_depend()
        return False

    if not clear and getSplitLibFile().exists() and (getSplitAsmDir().exists() and cfg.keep_objects):# and not isSymMapDiff():
        echo ("Split up to date")
        return False

    echo ("I'm Splector Gadget (may take a few minutes)!")
    if not clear:
        echo (" if you need to regenerate it later, run with \'-cs\'.")

    if getSplitAsmDir().exists():
        shutil.rmtree(getSplitAsmDir(), ignore_errors=True)
    if getSplitObjDir().exists():
        shutil.rmtree(getSplitObjDir(), ignore_errors=True)

    if cfg.split:
        import tools.splector as splector
        import tools.splector.split
    splector.split.main()

    if not getSplitAsmDir().exists():
        fail ("Splits are missing.")

    echo ("Recompiling splits")

    setup_compiler(cfg.compiler)

    getSplitObjDir().mkdir(parents=True, exist_ok=True)

    for asm in getSplitAsmDir().rglob("*.s"):
        output = getSplitObjDir() / asm.with_suffix(".o").name
        echo (f"> {output.name} <", "\r")

        asm_flags = flags_asm + ["-o", str(output), str(asm)]
        do_assemble(asm_flags)

        if not asm.name.startswith("a"):
            output.replace(getSplitPath() / output.name)

    echo ("Prelinking recomp")

    # generate .via
    via_path = getSplitPath() / "splector.via"

    with open(via_path, "w") as f:
        for s in getSplitObjDir().glob("*.o"):
            f.write(str(s))
            f.write(" ")

    out_name = str(getSplitObjFile())

    # prelink all objs
    flags_link = default_flags_link + ["--partial", f"--output={out_name}", f"--via={via_path}", "--no_map", "--no_symbols", "--no_locals"]
    do_link(flags_link, True)

    if not getSplitObjFile().exists():
        fail ("Splector recompilation is missing.")

    # strip debug
    flags_strip = [out_name, "--elf", "--strip=debug,comment,notes", "--output", out_name]
    do_export(flags_strip)

    if not getSplitObjFile().exists():
        fail ("Splector recompilation went missing while stripping.")

    # generate archive
    echo ("Archiving recomp")
    ar_path = str(getSplitLibFile())

    getBuildLibPath().mkdir(parents=True, exist_ok=True)

    flags_ar = ["-rcs", ar_path, str(getSplitObjFile())]
    do_archive(flags_ar)

    # cleanup
    if not cfg.keep_objects:
        shutil.rmtree(getSplitPath(), ignore_errors=True)

    return True
